import Sidebar from "@/components/Sidebar";
import "./globals.css";
import { Inter, Poppins } from "next/font/google";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight: ['400', '500'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body className={poppins.className}>
          <main className="absolute inset-0 bg-[#343541] text-white">{children}</main>
        </body>
      </Providers>
    </html>
  );
}
